#!/usr/bin/env bash

volume() {
  echo "$(pactl -f json get-sink-volume @DEFAULT_SINK@ | sed -n -r 's/.*?( [0-9]+%).*/\1/p' | tr -d '%' | cut -c 2-)"
}
microphone() {
  echo "$(pactl -f json get-source-volume @DEFAULT_SOURCE@ | sed -n -r 's/.*?( [0-9]+%).*/\1/p' | tr -d '%' | cut -c 2-)"
}

case "$1" in
"--vol")
  volume
  exit
  ;;
"--mic")
  microphone
  exit
  ;;
*)
  volume
  exit
  ;;
esac
